<?php
ini_set('display_errors',1);
ini_set('display_startup_erros',1);
error_reporting(E_ALL);

require_once('configs/config.php');

$query = "SELECT
					CATE1.ID_CATEGORIA ID_CATE1,
					CATE1.DESCRICAO_CATEGORIA DESC_CATE1,
					CATE1.URL_AMIGAVEL URL_CATE1,
					IFNULL(CATE1.CATE_ID_CATEGORIA,0) CATE_ID_CATE1,
					CATE2.ID_CATEGORIA ID_CATE2,
					CATE2.DESCRICAO_CATEGORIA DESC_CATE2,
					CATE2.URL_AMIGAVEL URL_CATE2,
					IFNULL(CATE2.CATE_ID_CATEGORIA,0) CATE_ID_CATE2,
					CATE3.ID_CATEGORIA ID_CATE3,
					CATE3.DESCRICAO_CATEGORIA DESC_CATE3,
					CATE3.URL_AMIGAVEL URL_CATE3,
					IFNULL(CATE3.CATE_ID_CATEGORIA,0) CATE_ID_CATE3
				FROM
					e_CATEGORIA CATE1,
					e_CATEGORIA CATE2 LEFT JOIN e_CATEGORIA CATE3
											 ON CATE2.ID_CATEGORIA = CATE3.CATE_ID_CATEGORIA,
					e_PRODUTO PROD,
					e_PRODUTO_CATEGORIA PRCA
				WHERE
					CATE1.CATE_ID_CATEGORIA IS NULL
				AND	CATE1.ATIVO = 'S'
				AND CATE2.CATE_ID_CATEGORIA = CATE1.ID_CATEGORIA
				AND PROD.ID_PRODUTO = PRCA.PROD_ID_PRODUTO
				AND PRCA.CATE_ID_CATEGORIA = CATE1.ID_CATEGORIA
				GROUP BY
					CATE1.ID_CATEGORIA,
					CATE1.DESCRICAO_CATEGORIA,
					CATE1.URL_AMIGAVEL,
					IFNULL(CATE1.CATE_ID_CATEGORIA,0),
					CATE2.ID_CATEGORIA,
					CATE2.DESCRICAO_CATEGORIA,
					CATE2.URL_AMIGAVEL,
					IFNULL(CATE2.CATE_ID_CATEGORIA,0),
					CATE3.ID_CATEGORIA,
					CATE3.DESCRICAO_CATEGORIA,
					CATE3.URL_AMIGAVEL,
					IFNULL(CATE3.CATE_ID_CATEGORIA,0),
					CATE1.ORDEM, CATE2.ORDEM, CATE3.ORDEM
				ORDER BY
					CATE1.ORDEM ASC, CATE1.DESCRICAO_CATEGORIA ASC,
					CATE2.ORDEM ASC, CATE2.DESCRICAO_CATEGORIA ASC,
					CATE3.ORDEM ASC, CATE3.DESCRICAO_CATEGORIA ASC";

	$result = $mysqli->ConsultarSQL($query);
	printr($result);


?>