<?php 
 /*Data: 08/07/2014 14:54:53*/ 
define('TABELA_PRECO_COMPRA_PADRAO', '1');
define('TABELA_PRECO_VENDA_PADRAO', '1');
define('TABELA_PRECO_VENDA_PROMOCIONAL', '2');
define('ID_ATRIBUTO_VALOR_PADRAO', '16');
define('NUMERO_MAXIMO_PARCELAS', '12');
define('VALOR_PARCELA_MINIMA', '10');
define('VALOR_PACOTE_PRESENTE', '2');
define('ID_SITUACAO_PEDIDO_ATENDIDO', '5');
define('PESO_MAXIMO_CORREIOS', '30');
define('ID_TIPO_FRETE_TRANSP_PADRAO', '1');
define('ID_CATEGORIA_PADRAO_1', '4987');
define('ID_CATEGORIA_PADRAO_2', '4988');
define('PESO_MINIMO_INSERT_PRODUTO', '2');
define('ID_OPERACAO_DEPOSITO_INICIAL', '1');
define('ID_DEPOSITO_INICIAL', '1');
define('ID_PESSOA_FABRICANTE', '3');
define('VALOR_MINIMO_LIBERA_PRODUTO_VENDA', '0.1');
define('TABELA_PRODUTO_SITE', 'vw_tabela_produto_site');
define('DESCONTO_FORMA_PAGAMENTO_BOLETO', '10');
define('ID_PESSOA_CATEGORIA_CLIENTE', '11');
define('ID_OPERACAO_DEPOSITO_SAIDA_RESERVA_PEDIDO', '7');
define('ID_SITUACAO_PEDIDO_DIGITACAO', '1');
define('ID_SITUACAO_PEDIDO_TIMEOUT', '9');
define('ID_SITUACAO_PEDIDO_CANCELADO', '7');
define('ID_SITUACAO_PEDIDO_ESTORNADO', '18');
define('ID_SITUACAO_PEDIDO_REEMBOLSADO', '19');
define('ID_SITUACAO_PEDIDO_ANALISE_CREDITO', '2');
define('ID_SITUACAO_PEDIDO_APROVADO_CREDITO', '3');
define('ID_SITUACAO_PEDIDO_PROD_INDISPONIVEL', '13');
define('ID_SITUACAO_PEDIDO_NEGADO_CREDITO', '4');
define('ID_SITUACAO_PEDIDO_DESPACHADO', '10');
define('COD_EMPRESA_CORREIOS', '09161830');
define('SENHA_EMPRESA_CORREIOS', '90005307');
define('CEP_ORIGEM', '95180000');
define('MARKUP', '2');
?>